### ISSUE TITLE
Probability overlapping

### ISSUE THREAD

**Issue by Yukun-Xie** [KWR-Water/pysimdeum#19] opened 2022-09-20 12:41 UTC
Once an event happens, the probability distribution should be revised and renormalized again. Otherwise, for an end use with long time duration, events will overlap. For example, washing machine and shower.
**Possible solution:**
prob_joint = normalize(prob_user * prob_usage)
j = len(users)
freq = self.fct_frequency(numusers=len(users))
for _ in range(freq):
    duration, intensity = self.fct_duration_intensity()
    u = np.random.uniform()
    start = np.argmin(np.abs(np.cumsum(prob_joint) - u))
    end = start + duration
    consumption[start:end, j, ind_enduse, pattern_num] = intensity
                
    prob_joint[start - duration + 1:start + duration] = 0
    prob_joint = normalize(prob_joint)

**Comment by BramHillebrand** [comment] 2024-08-29 12:42
But end uses are allowed to overlap by design. Close issue as wont fix

**Closed by BramHillebrand** 2024-08-29 12:42 UTC
Labels: wontfix
